const SET_SELECTED_SHIPPING_ADDRESS = 'SET_SELECTED_SHIPPING_ADDRESS';
const SET_SELECTED_BILLING_ADDRESS = 'SET_SELECTED_BILLING_ADDRESS';

const SET_SELECTED_SUBSCRIPTION = 'SET_SELECTED_SUBSCRIPTION';
const ADD_SUBSCRIPTION_TO_CART = 'ADD_SUBSCRIPTION_TO_CART';
const REMOVE_SUBSCRIPTION_FROM_CART = 'REMOVE_SUBSCRIPTION_FROM_CART';
const CLEAN_CART = 'CLEAN_CART';

const SET_DELIVERY_DAY_OF_WEEK = 'SET_DELIVERY_DAY_OF_WEEK';
const SET_DELIVERY_TIME = 'SET_DELIVERY_TIME';

export default {
  SET_SELECTED_SUBSCRIPTION,
  SET_SELECTED_BILLING_ADDRESS,
  SET_SELECTED_SHIPPING_ADDRESS,
  ADD_SUBSCRIPTION_TO_CART,
  REMOVE_SUBSCRIPTION_FROM_CART,
  CLEAN_CART,
  SET_DELIVERY_DAY_OF_WEEK,
  SET_DELIVERY_TIME,
};
