import { getAsyncActionType } from '../../utils/redux';

const SET_SELECTED_ORDER = 'SET_SELECTED_ORDER';
const CANCEL_ORDER = 'CANCEL_ORDER';
const CHANGE_ORDER_DELIVERY_SCHEDULE = 'CHANGE_ORDER_DELIVERY_SCHEDULE';
const CHANGE_ORDER_SHIPPING_ADDRESS = 'CHANGE_ORDER_SHIPPING_ADDRESS';

export default {
  SET_SELECTED_ORDER,
  ...getAsyncActionType(CANCEL_ORDER),
  ...getAsyncActionType(CHANGE_ORDER_DELIVERY_SCHEDULE),
  ...getAsyncActionType(CHANGE_ORDER_SHIPPING_ADDRESS),
};
